# This file should contain everything to configure the workflow on a global scale.
# In case of sample based data, it should be complemented by a samples.tsv file that contains
# one row per sample. It can be parsed easily via pandas.
samples: "config/samples.tsv"

threads: 24

params:
    trim:
        - "--quality 20"
        - "--phred33"
        - "--fastqc"
        - "--fastqc_args \"--threads 6\""
        - "--trim-n"
        - "--trim1"
        - "--paired"
    spades:
        - "--only-assembler"
        - "--careful"
        - "-k 21,23,25,27,29,31,33,35,37,39,41,43,45,47,49,51,53,55,57,59,61,63,65,67,69,71,73,75,77,79,81,83,85,87,89,91,93,95,97,99,101,103,105,107,109,111,113,115,117,119,121,123,125,127"
        - "--cov-cutoff auto"
    quast:
        - "--min-contig 1000"
        - "--circos"
        - "--glimmer"
        - "--rna-finding"
        - "--conserved-genes-finding"
    seqkit:
        - "--min-len 1000"
        - "-g"
    skesa:
        - "--memory 120"
        - "--hash_count"
        - "--steps 53"
    prokka:
        - "--addgenes"
        - "--centre LaCTAD"
        - "--mincontiglen 1000"
        - "--rfam"
        - "--proteins "

   